runtime: nodejs14

env_variables:
  MYSQL_USER: orang
  MYSQL_PASSWORD: pass
  MYSQL_DATABASE: data
  INSTANCE_CONNECTION_NAME: if-g-01:us-central1:dbku

# Ganti <nama_instance_connection> dengan nilai Instance Connection Name dari Google Cloud SQL Anda
